---
- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true

- name: Start and enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
