- hosts: localhost
  pre_tasks:
    - name: Load default variables
      include_vars: group_vars/all.yaml
    - name: Generate dynamic defaults
      import_tasks: ./tasks/generate_defaults.yaml
    - name: Generate SSH key for guest access
      ansible.builtin.openssh_keypair:
        path: "{{ playbook_dir }}/ansible_key"
        type: rsa
        size: 2048
        owner: "{{ vm_username }}"
        mode: '0600'
    - name: Generate inventory file
      ansible.builtin.template:
        src: templates/inventory.j2
        dest: "{{ playbook_dir }}/inventory"
    - name: Refresh inventory to ensure new hosts are available
      ansible.builtin.meta: refresh_inventory
  roles:
    - ../roles/libvirt_provision

- hosts: k8s_cluster
  roles:
    - ../roles/kubernetes
