---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  changed_when: false

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  # register: apt_docker_repo
  # retries: 10
  # delay: 5
  # until: apt_docker_repo is success

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: true
  become: true
  # register: install_containerd
  # retries: 10
  # delay: 5
  # until: install_containerd is success

- name: Configure containerd
  ansible.builtin.shell: |
    containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
    sed -i '/sandbox_image/s|registry.k8s.io/pause:3.8|registry.k8s.io/pause:3.10|' /etc/containerd/config.toml
  become: true
  changed_when: false

- name: Restart and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
  become: true
