---
- name: Import prerequisites tasks
  ansible.builtin.import_tasks: prerequisites.yaml

- name: Import containerd setup tasks
  ansible.builtin.import_tasks: containerd.yaml

- name: Import kubernetes setup tasks
  ansible.builtin.import_tasks: kubernetes.yaml

- name: Import network components tasks
  ansible.builtin.import_tasks: network.yaml

- name: Import tools tasks
  ansible.builtin.import_tasks: tools.yaml
