---
- name: Install Cilium CLI
  when: inventory_hostname == 'controlplane01'
  block:
    - name: Get latest Cilium CLI version
      ansible.builtin.shell: curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
      register: cilium_version

    - name: Download and install Cilium CLI
      ansible.builtin.shell: |
        CLI_ARCH=amd64
        if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
        curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version.stdout }}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
        sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
        sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
        rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

- name: Install Hubble CLI
  when: inventory_hostname == 'controlplane01'
  block:
    - name: Get latest Hubble version
      ansible.builtin.shell: curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt
      register: hubble_version

    - name: Download and install Hubble CLI
      ansible.builtin.shell: |
        HUBBLE_ARCH=amd64
        if [ "$(uname -m)" = "aarch64" ]; then HUBBLE_ARCH=arm64; fi
        curl -L --fail --remote-name-all https://github.com/cilium/hubble/releases/download/{{ hubble_version.stdout }}/hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
        sha256sum --check hubble-linux-${HUBBLE_ARCH}.tar.gz.sha256sum
        sudo tar xzvfC hubble-linux-${HUBBLE_ARCH}.tar.gz /usr/local/bin
        rm hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}

- name: Install Helm
  when: inventory_hostname == 'controlplane01'
  block:
    - name: Add Helm apt key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
      become: true

    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
      become: true

    - name: Install Helm package
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: true
      become: true

    - name: Add Cilium Helm repository
      ansible.builtin.shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
      changed_when: false

    - name: Install Cilium using Helm
      ansible.builtin.shell: |
        helm install cilium cilium/cilium --version 1.17.0-rc.0 --namespace kube-system -f ~/cilium-values.yaml
      args:
        creates: /var/lib/kubernetes/.cilium_installed
